[package]
name = "unpac"
version = "1.0.0"
authors = ["super-continent"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binread = "1.4"
anyhow = "1.0"
structopt = "0.3"
miniserde = "0.1"
byteorder = "1.4"
